export const SET_CURRENT_PICTURE = 'SET_CURRENT_PICTURE';
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
export const UPLOAD_PICTURE_ERROR = 'UPLOAD_PICTURE_ERROR';
export const DISCARD_PICTURE = 'DISCARD_PICTURE';